#ifndef MAG_RAWHID_H
#define MAG_RAWHID_H

#include <stdint.h>

#define MAG_RAWHID_PROTOCOL_VERSION 1
#define MAG_RAWHID_COMMAND_ID 0x4D

typedef enum {
    MAG_RAWHID_STATUS_OK = 0,
    MAG_RAWHID_STATUS_ERROR = 1,
    MAG_RAWHID_STATUS_BAD_COMMAND = 2,
    MAG_RAWHID_STATUS_BAD_BLOCK = 3,
    MAG_RAWHID_STATUS_BAD_LENGTH = 4,
} mag_rawhid_status_t;

typedef enum {
    MAG_RAWHID_CMD_GET_INFO = 1,
    MAG_RAWHID_CMD_READ_BLOCK = 2,
    MAG_RAWHID_CMD_WRITE_BLOCK = 3,
    MAG_RAWHID_CMD_SAVE_BLOCK = 4,
    MAG_RAWHID_CMD_RESET_BLOCK = 5,
    MAG_RAWHID_CMD_READ_D_CUR = 6,
    MAG_RAWHID_CMD_GET_STATE = 7,
    MAG_RAWHID_CMD_SET_STATE = 8,
    MAG_RAWHID_CMD_CAL_CONTROL = 9,
    MAG_RAWHID_CMD_GET_CAL_STATE = 10,
    MAG_RAWHID_CMD_READ_CAL_VIEW = 11,
    MAG_RAWHID_CMD_RUN_PCB_CAL = 12,
    MAG_RAWHID_CMD_READ_ADC_CUR = 13,
    MAG_RAWHID_CMD_READ_REALTIME_KEY = 14,
} mag_rawhid_command_t;

#endif
